
os: linux

arch:
  - s390x

dist: focal

python:
  - "3.9"

branches:
  only:
  - master
  - devel

before_install:
  # https://conda.io/projects/conda/en/latest/user-guide/tasks/use-conda-with-travis-ci.html
  - wget https://repo.anaconda.com/miniconda/Miniconda3-py39_4.10.1-Linux-s390x.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

install:
  - make create_environment
  - conda activate SMARTER-database
  - make requirements

script:
  - tox

# after_script:
#   - coveralls
