name: SMARTER-database

channels:
  - bioconda
  - conda-forge
  - nodefaults

dependencies:
  - python=3.12
  - pip
  - poetry=1.8
  - plink
  - tabix
  - vcftools
  - bcftools

# Non-standard section listing target platforms for conda-lock:
platforms:
  - linux-64
