
# User/password credentials are stored in .env file
version: '3.2'

services:

  mongo:
    image: mongo:4.4

    container_name: smarter-database_mongo

    ports:
      - 27017:27017

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASS}
      MONGO_INITDB_DATABASE: 'smarter'
      HOME: /home/mongodb

    # to export volume, as recommeded in https://registry.hub.docker.com/u/library/mysql/
    volumes:
      - type: bind
        source: ./mongodb-data
        target: /data/db

      - type: bind
        source: ./mongodb-home
        target: /home/mongodb

      - type: bind
        source: ./docker-entrypoint-initdb.d
        target: /docker-entrypoint-initdb.d

    networks:
      - smarter-database


  express:
    image: mongo-express:0.54

    container_name: smarter-database_express

    ports:
      - 8081:8081

    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_ROOT_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_ROOT_PASS}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGOEXPRESS_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGOEXPRESS_PASS}

    networks:
      - smarter-database


networks:
  smarter-database:
